// This file is automatically generated. Do not edit it directly.
// API endpoints and URLs
// TODO: Replace with your actual Airtable API key and Base ID.
export const AIRTABLE_API_KEY = "YOUR_AIRTABLE_API_KEY_HERE";
export const AIRTABLE_BASE_ID = "YOUR_AIRTABLE_BASE_ID_HERE";

// Application metadata
export const APP_NAME = "Reminders";
export const APP_SUPPORT_EMAIL = "dialchimpstudio@gmail.com";

// Table names
export const TABLE_USER_PROFILES = "user_profiles";
export const TABLE_REMINDERS = "reminders";

// Toast durations
export const TOAST_DURATION = 2000;

// Routes
export const ROUTES = {
  HOME: "/",
  AUTH: "/auth",
  REMINDERS: "/reminders",
  REMINDERS_NEW: "/reminders/new",
  REMINDERS_MANAGE: "/reminders/manage",
  SETTINGS: "/settings",
  ADMIN_USERS: "/admin/users",
  ADMIN_REMINDERS: "/admin/reminders",
};

// User messages
export const MESSAGES = {
  ACCESS_DENIED: "You don't have permission to view this page.",
  ACCOUNT_DISABLED: "Your account has been disabled by an administrator.",
  USER_PROMOTED: "User promoted to admin",
  USER_DEMOTED: "User removed from admin role",
  USER_ACTIVATED: "User activated",
  USER_DEACTIVATED: "User deactivated",
  FAILED_LOAD_USERS: "Failed to load users",
  FAILED_LOAD_USERS_DESC: "There was a problem loading the user list.",
  ACTION_FAILED: "Action Failed",
};