// This file contains mock data to simulate your Airtable base.
// In a real application, this data would come from API calls.

export const MOCK_REMINDERS_DATA = [
  {
    id: "rec1",
    user_id: "user123",
    category: "Subscription",
    subcategory: "Netflix",
    provider: "Netflix",
    description: "Yearly subscription for Netflix",
    cost: 120,
    frequency: "Yearly",
    expiry_date: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 15).toISOString(),
    active: true,
    currency: "GBP",
    created_at: "2023-01-01T00:00:00Z",
  },
  {
    id: "rec2",
    user_id: "user123",
    category: "Mobile Plan",
    subcategory: "iPhone Plan",
    provider: "Vodafone",
    description: "Monthly mobile plan",
    cost: 45,
    frequency: "Monthly",
    expiry_date: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() + 5).toISOString(),
    active: true,
    currency: "GBP",
    created_at: "2023-01-01T00:00:00Z",
  },
  {
    id: "rec3",
    user_id: "user123",
    category: "Insurance",
    subcategory: "Car Insurance",
    provider: "Admiral",
    description: "Car insurance policy renewal",
    cost: 500,
    frequency: "Yearly",
    expiry_date: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() - 10).toISOString(),
    active: true,
    currency: "GBP",
    created_at: "2023-01-01T00:00:00Z",
  },
  {
    id: "rec4",
    user_id: "admin456",
    category: "Energy Plan",
    subcategory: "Gas",
    provider: "British Gas",
    description: "Annual gas bill",
    cost: 1200,
    frequency: "Yearly",
    expiry_date: new Date(new Date().getFullYear(), new Date().getMonth() + 2, 20).toISOString(),
    active: true,
    currency: "GBP",
    created_at: "2023-01-01T00:00:00Z",
  },
  {
    id: "rec5",
    user_id: "user789",
    category: "Subscription",
    subcategory: "Spotify",
    provider: "Spotify",
    description: "Monthly Spotify premium",
    cost: 10,
    frequency: "Monthly",
    expiry_date: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() + 1).toISOString(),
    active: true,
    currency: "USD",
    created_at: "2023-01-01T00:00:00Z",
  },
];

export const MOCK_USER_PROFILES_DATA = [
  {
    id: "user123",
    email: "user@example.com",
    name: "Regular User",
    created_at: "2023-01-01T00:00:00Z",
    is_active: true,
    is_admin: false,
    preferred_currency: "GBP",
  },
  {
    id: "admin456",
    email: "admin@example.com",
    name: "Admin User",
    created_at: "2023-01-01T00:00:00Z",
    is_active: true,
    is_admin: true,
    preferred_currency: "USD",
  },
  {
    id: "user789",
    email: "inactive@example.com",
    name: "Inactive User",
    created_at: "2023-01-01T00:00:00Z",
    is_active: false,
    is_admin: false,
    preferred_currency: "EUR",
  },
];